source "https://rubygems.org"

gem "rails", "~> 7.0"
gem "pg", ">= 1.1"
gem "puma", "~> 5.0"
gem "redis", "~> 5.0"

group :development, :test do
  gem "rspec", "~> 3.12"
  gem "rubocop", "~> 1.50"
  gem "debug"
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
