"""Report formatter — generate GRAPH_REPORT.md and analysis.json.

Produces:
- ``GRAPH_REPORT.md`` — human/LLM-readable analysis report with tables
- ``analysis.json`` — machine-readable analysis results

Both files are deterministic for identical input.
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from ast_intel.core.analyzer import (
    Community,
    GodNode,
    GraphAnalysis,
    Hyperedge,
    SurprisingConnection,
)

__all__: list[str] = [
    "ANALYSIS_JSON_FILENAME",
    "GRAPH_REPORT_FILENAME",
    "ReportFormatter",
]

logger = logging.getLogger(__name__)

GRAPH_REPORT_FILENAME: str = "GRAPH_REPORT.md"
ANALYSIS_JSON_FILENAME: str = "analysis.json"

# Maximum members to display inline in hyperedge tables.
_MAX_INLINE_MEMBERS: int = 5


# ---------------------------------------------------------------------------
# region:    --- JSON Encoder
# ---------------------------------------------------------------------------


class _AnalysisEncoder(json.JSONEncoder):
    """Custom JSON encoder that handles analysis dataclasses and tuples."""

    def default(self, o: object) -> Any:  # noqa: ANN401
        if isinstance(o, (GodNode, SurprisingConnection, Community, Hyperedge)):
            return asdict(o)
        if isinstance(o, tuple):
            return list(o)
        return super().default(o)


# endregion: --- JSON Encoder


# ---------------------------------------------------------------------------
# region:    --- ReportFormatter
# ---------------------------------------------------------------------------


class ReportFormatter:
    """Serialize :class:`~ast_intel.core.analyzer.GraphAnalysis` to files.

    Generates two output files:

    - ``GRAPH_REPORT.md`` — Markdown tables and narrative text.
    - ``analysis.json`` — Machine-readable JSON.
    """

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def write(
        self,
        analysis: GraphAnalysis,
        output_dir: Path,
    ) -> tuple[Path, Path]:
        """Write both report files and return their paths.

        Args:
            analysis: The completed ``GraphAnalysis`` from the analyzer.
            output_dir: Directory to write into (created if needed).

        Returns:
            ``(report_md_path, analysis_json_path)``.
        """
        output_dir.mkdir(parents=True, exist_ok=True)

        md_path = output_dir / GRAPH_REPORT_FILENAME
        json_path = output_dir / ANALYSIS_JSON_FILENAME

        md_content = self._render_markdown(analysis)
        md_path.write_text(md_content, encoding="utf-8")
        logger.info("Wrote %s (%d bytes)", md_path, len(md_content))

        json_content = self._serialize_json(analysis)
        json_path.write_text(json_content, encoding="utf-8")
        logger.info("Wrote %s (%d bytes)", json_path, len(json_content))

        return md_path, json_path

    # ------------------------------------------------------------------
    # Markdown rendering
    # ------------------------------------------------------------------

    def _render_markdown(self, analysis: GraphAnalysis) -> str:
        """Render the full GRAPH_REPORT.md content."""
        lines: list[str] = []
        lines.append("# AST Intel — Graph Analysis Report\n")
        lines.append(
            f"> Generated {datetime.now(tz=UTC):%Y-%m-%d %H:%M:%S UTC}  \n"
            f"> Modularity: {analysis.modularity:.4f}\n",
        )

        self._render_god_nodes(lines, analysis.god_nodes)
        self._render_communities(lines, analysis.communities)
        self._render_surprising(lines, analysis.surprising_connections)
        self._render_hyperedges(lines, analysis.hyperedges)
        self._render_similarity_clusters(lines, analysis.hyperedges)
        self._render_questions(lines, analysis.suggested_questions)

        lines.append(
            "\n---\n*This report was generated by AST Intel graph analysis.*\n",
        )
        return "\n".join(lines)

    @staticmethod
    def _render_god_nodes(
        lines: list[str], god_nodes: list[GodNode],
    ) -> None:
        """Render the God Nodes table."""
        lines.append("\n## God Nodes (Highest Connectivity)\n")
        if not god_nodes:
            lines.append("_No high-connectivity nodes detected._\n")
            return

        lines.append(
            "| Rank | Symbol | Kind | Degree (In/Out) "
            "| Community | Communities Bridged |",
        )
        lines.append(
            "|------|--------|------|-----------------|"
            "-----------|---------------------|",
        )
        for rank, gn in enumerate(god_nodes, 1):
            lines.append(
                f"| {rank} | `{gn.label}` | {gn.kind} "
                f"| {gn.degree} ({gn.in_degree}/{gn.out_degree}) "
                f"| {gn.community} | {gn.connected_communities} |",
            )

    @staticmethod
    def _render_communities(
        lines: list[str], communities: list[Community],
    ) -> None:
        """Render the Communities table."""
        lines.append("\n## Communities (Clusters)\n")
        if not communities:
            lines.append("_No community structure detected._\n")
            return

        lines.append("| ID | Label | Nodes | Internal Edges | Key Symbols |")
        lines.append("|----|-------|-------|----------------|-------------|")
        for c in communities:
            key_labels = ", ".join(
                f"`{k.rsplit('::', maxsplit=1)[-1]}`" for k in c.key_nodes[:3]
            )
            lines.append(
                f"| {c.id} | {c.label} | {c.node_count} "
                f"| {c.internal_edge_count} | {key_labels} |",
            )

    @staticmethod
    def _render_surprising(
        lines: list[str],
        connections: list[SurprisingConnection],
    ) -> None:
        """Render the Surprising Connections table."""
        lines.append("\n## Surprising Connections\n")
        if not connections:
            lines.append("_No cross-community surprises detected._\n")
            return

        lines.append("| # | Connection | Score | Why |")
        lines.append("|---|-----------|-------|-----|")
        for idx, sc in enumerate(connections[:20], 1):
            src_label = sc.source_id.rsplit("::", maxsplit=1)[-1]
            tgt_label = sc.target_id.rsplit("::", maxsplit=1)[-1]
            lines.append(
                f"| {idx} | `{src_label}` → `{tgt_label}` "
                f"| {sc.surprise_score:.2f} | {sc.why} |",
            )

    @staticmethod
    def _render_hyperedges(
        lines: list[str], hyperedges: list[Hyperedge],
    ) -> None:
        """Render the Hyperedges section."""
        lines.append("\n## Hyperedges (Group Relationships)\n")
        if not hyperedges:
            lines.append("_No group relationships (≥3 members) detected._\n")
            return

        lines.append("| Label | Kind | Members |")
        lines.append("|-------|------|---------|")
        for he in hyperedges:
            member_labels = ", ".join(
                f"`{m.rsplit('::', maxsplit=1)[-1]}`"
                for m in he.members[:_MAX_INLINE_MEMBERS]
            )
            if len(he.members) > _MAX_INLINE_MEMBERS:
                member_labels += (
                    f" + {len(he.members) - _MAX_INLINE_MEMBERS} more"
                )
            lines.append(
                f"| {he.label} | {he.kind} | {member_labels} |",
            )

    @staticmethod
    def _render_similarity_clusters(
        lines: list[str], hyperedges: list[Hyperedge],
    ) -> None:
        """Render the Similarity Clusters section (SHARED_SIMILARITY only)."""
        from ast_intel.core.analyzer import HyperedgeKind

        clusters = [
            he for he in hyperedges
            if he.kind == HyperedgeKind.SHARED_SIMILARITY
        ]
        lines.append("\n## Similarity Clusters\n")
        if not clusters:
            lines.append("_No similarity clusters detected._\n")
            return

        lines.append("| Cluster | Members |")
        lines.append("|---------|---------|")
        for cl in clusters:
            member_labels = ", ".join(
                f"`{m.rsplit('::', maxsplit=1)[-1]}`"
                for m in cl.members[:_MAX_INLINE_MEMBERS]
            )
            if len(cl.members) > _MAX_INLINE_MEMBERS:
                member_labels += (
                    f" + {len(cl.members) - _MAX_INLINE_MEMBERS} more"
                )
            lines.append(f"| {cl.label} | {member_labels} |")

    @staticmethod
    def _render_questions(
        lines: list[str], questions: list[str],
    ) -> None:
        """Render the Suggested Questions section."""
        lines.append("\n## Suggested Questions\n")
        if not questions:
            lines.append("_No suggested questions generated._\n")
            return

        for idx, q in enumerate(questions, 1):
            lines.append(f"{idx}. {q}")

    # ------------------------------------------------------------------
    # JSON serialization
    # ------------------------------------------------------------------

    def _serialize_json(self, analysis: GraphAnalysis) -> str:
        """Serialize analysis to deterministic JSON."""
        payload: dict[str, Any] = {
            "generated_at": datetime.now(tz=UTC).isoformat(),
            "modularity": round(analysis.modularity, 6),
            "god_nodes": [asdict(gn) for gn in analysis.god_nodes],
            "communities": [self._community_dict(c) for c in analysis.communities],
            "surprising_connections": [
                asdict(sc) for sc in analysis.surprising_connections
            ],
            "hyperedges": [self._hyperedge_dict(he) for he in analysis.hyperedges],
            "suggested_questions": analysis.suggested_questions,
        }
        return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"

    @staticmethod
    def _community_dict(c: Community) -> dict[str, Any]:
        """Convert a Community to a JSON-safe dict (tuple → list)."""
        d: dict[str, Any] = asdict(c)
        d["key_nodes"] = list(c.key_nodes)
        return d

    @staticmethod
    def _hyperedge_dict(he: Hyperedge) -> dict[str, Any]:
        """Convert a Hyperedge to a JSON-safe dict (tuple → list)."""
        d: dict[str, Any] = asdict(he)
        d["members"] = list(he.members)
        return d


# endregion: --- ReportFormatter
